name: Exploring Variables and Secres

on:
    push
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: siddharth1
    DOCKER_PASSWORD: s3cUrePaSsw0rd
    IMAGE_NAME: github-action-nginx
jobs:
  
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest 

    - name: Docker login
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    
    - name: Docker publish
      run: echo docker push docker.io/dockerUsername/imageName:latest
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
      