name: My First workflows

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "my first Github Actions Job"

        - name:
          run: ls

        - name:
          run: cat README.md


