name: First_workflows_Actions

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v5


        - name: List and Read file
          run: |
            echo "Hello my first Actions job"
            ls -ltra
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt