name: Generate ASCII Artwork

on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3  
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Executing Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
    
    - name: Sleep for 30 seconds
      run: sleep 30

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest  
    steps: 
    - name: Sleep for 30 seconds
      run: sleep 30

    - name: Test File Exists
      run: grep -i "dragon" fragon.txt

  deploy_job_3:
    
    needs: [test_job_2 , build_job_1]
    runs-on: ubuntu-latest  
    steps:
    - name: Read File
      run: cat dragon.txt
    
    - name: Deploy
      run: echo Deploying ... ... .
    
  
