name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3  

    - name:  List Repo Files
      run: ls -ltra

    - name: MyPath
      run: pwd

    - name: change Dir
      run: cd workspaces/action-1/.github/workflows/
      
    - name: Executing shell Script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh
    
  
