name: Matrix Configuration

on:
    push:
    workflow_dispatch:
jobs:
    deploy:
      strategy:
        matrix:
            os: [ubuntu-latest , ubuntu-20.04 , windows-latest]
            images: [hello-world , nginx:latest , alpine:latest]
      runs-on: ${{matrix.os}}
      steps:
        - name: Echo Docker Info
          run: docker info

        - name: Run image ${{matrix.images}}
          run: docker run ${{matrix.images}}


